---
- name: update packages
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes
    
- name: Installing NPM
  apt:
    name: "{{ item }}"
    state: latest
  loop: ['npm', 'nodejs']

- name: Installing pm2
  npm: 
    name: pm2
    state: present
    global: true
    production: true 