---
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: xtract the zipped artifact into the EC2 instance
  unarchive:
    src: /root/project/artifact.tar.gz
    #src: ../../../../artifact.tar.gz
    dest: /home/ubuntu

- name: Executing node
  shell: |
    cd /home/ubuntu/backend
    npm -g npm@latest
    npm run build
    pm2 start npm --name backend -- start
    #sudo npm install
    #sudo npm audit fix --force
    #sudo pm2 stop default
    #sudo pm2 start npm -- run start
    #cd dist
    #sudo pm2 start main.js --update-env