---
- name: xtract the zipped artifact into the EC2 instance
  ansible.builtin.unarchive:
    src: ~/udacity-project/projects/cdond-c3-projectstarter/artifact.tar.gz
    dest: /home/ubuntu

- name: Intall the appp
  shell: npm install
  args:
      chdir: /home/ubuntu

- name: Change the working directory to somedir/ before executing the command
  shell: pm2 stop default
  args:
    chdir: /home/ubuntu

- name: Change the working directory to somedir/ before executing the command
  shell: pm2 start npm -- start
  args:
    chdir: /home/ubuntu