version: '2.1'
orbs:
  slack: circleci/slack@4.1
#########################COMMANDS############################################
commands:
  destroy-environment:
    description: destroy backend & frontend
    parameters:
      workflowid:
        type: string
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: delete S3 content
          when: on_fail
          command: |
            aws s3 rm s3://udapeople-<<parameters.workflowid>> --recursive --region us-east-1
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
      #- revert-migrations:
      #    workflowid: << parameters.workflowid >>

  revert-migrations:
      description: Revert.
      parameters:
        workflowid:
          type: string
          default: ${CIRCLE_WORKFLOW_ID:0:7}
      steps:
        - restore_cache:
            key: backend-build
        - run:
            name: Revert migrations
            when: on_fail
            command: |
              SUCCESS=`curl --insecure https://kvdb.io/97DDVfQqUVMSzD5WALik4Y/values/migration_${CIRCLE_WORKFLOW_ID:0:7}'
              echo $SUCCESS
              if [[ $SUCCESS == 1 ]];
              then
                cd ~/project/backend
                npm install
                npm run migrations:revert 
              fi 

#####################JOBS###########################################################
jobs:
#########################BUILD-BACKEND####################################
  build-frontend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys: [frontend-build]
        - run:
            name: Build front-end
            command: |
              # Your code here and here dsdesd
              cd frontend
              npm install
              npm run build
              npm audit fix --audit-level=critical --force
        - slack/notify:
            channel: udapeople
            event: fail
            template: basic_fail_1
        - save_cache:
            key: frontend-build
            paths: [frontend/node_modules]
#########################BUILD-BACKEND####################################
  build-backend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys: [backend-build]
        - run:
            name: Back-end build
            command: |
              # Your code here
              cd backend
              npm install
              npm run build
              npm audit fix --audit-level=critical --force
        - slack/notify:
            channel: udapeople
            event: fail
            template: basic_fail_1       
        - save_cache:
            key: build-backend
            paths: [backend/node_modules ] 
        - run:
            name: Compiled code will be retrieved by deploy-backend.yml 
            command: |
              mkdir /tmp/workspace/
              cp ./backend/package.json /tmp/workspace/
              cd backend/dist
              tar -zcvf /tmp/workspace/backend.tgz ./
              tar -zcvf ./../../backend.tgz ./
        - slack/notify:
            channel: udapeople
            event: fail
            template: basic_fail_1
        - persist_to_workspace:
            root: /tmp/workspace
            paths:
              - package.json
              - backend.tar.gz 
#########################TESTING-FRONTEND####################################
  test-frontend:
      docker:
        # Docker image here
        - image: circleci/node:13.8.0
      steps:
        # Checkout code from git
        - checkout
        # Restore from cache
        - restore_cache:
            keys: [frontend-build]
        # Your job code here
        - run:
            name: Frontend unit test
            command: |
              cd frontend
              sudo npm i
              npm run test
        - slack/notify:
            channel: udapeople
            event: fail
            template: basic_fail_1

#########################TESTING-BACKEND#####################################
  test-backend:
      docker:
        # Docker image here
        - image: circleci/node:13.8.0
      steps:
        # Checkout code from git
        - checkout
        # Restore from cache
        - restore_cache:
            keys: [backend-build]
        # Your job code here
        - run:
            name: test backend
            command: |
              cd backend
              npm i
              npm run test
        - slack/notify:
            channel: udapeople
            event: fail
            template: basic_fail_1

########################SCANNING-FRONT-END###################################
  scan-frontend:
      docker:
        # Docker image here
        - image: circleci/node:13.8.0
      steps:
        # Checkout code from git
        - checkout
        # Restore from cache
        - restore_cache:
            keys: [frontend-build]
        # Your job code here
        - run:
            name: scanning frontend
            command: |
              cd frontend
              npm i
              npm audit fix --audit-level=critical --force
        - slack/notify:
            channel: udapeople
            event: fail
            template: basic_fail_1
#######################################SCANNING-BACKEND######################

  scan-backend:
    docker:
      # Docker image here
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout 
      # Restore from cache
      - restore_cache:
          keys: [backend-build]
      # Your job code here
      - run:
          name: scanning backend
          command: |
            cd backend
            npm i
            npm audit fix --audit-level=critical --force
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1

################DEPLOY-INFRASTRUCTURE########################################
  deploy-infrastructure:
    docker:
      # Docker image here that supports AWS CLI
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: installing packages
          command: |
            yum -y install tar gzip git
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            # Use the workflow id to mark your CloudFormation stacks so that you can reference them later on (ex: rollback). 
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=udapeople\
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
              --region us-east-1
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=udapeople\
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"\
              --region us-east-1
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            # Your code here  Remove this filter fromm the code below #--filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text >> .circleci/ansible/inventory.txt --region us-east-1
              cat .circleci/ansible/inventory.txt
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      # Here's where you will add some code to rollback on failure   
      - destroy-environment:
          workflowid: "${CIRCLE_WORKFLOW_ID:0:7}"
######################CONFIGURE-INFRASTRUCTURE###############################
  configure-infrastructure:
    docker:
      # Docker image here that supports Ansible
      - image: python:3.7-alpine3.11
    steps:
      # Checkout code from git
      - checkout
      - restore_cache:
          key: frontend-build
      # Add ssh keys with fingerprint
      - add_ssh_keys:
          fingerprints: ["a1:6f:c8:51:94:d4:0c:fd:45:00:67:75:29:c4:cd:2f"]
      # attach workspace
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            # Your code here
            apk add --update ansible openssh-client tar gzip curl
            apk update pip3
            pip3 install awscli
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1
      - run:
          name: Configure server
          command: |
            # Your code here
            cd backend
            touch ".env"
            echo ENVIRONMENT=production > ".env"
            echo TYPEORM_CONNECTION=postgres >> ".env"
            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ".env"
            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
            echo NODE_ENV=production >> ".env"
            echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
            echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
            cd ..            
            export ANSIBLE_HOST_KEY_CHECKING=False
            cd .circleci/ansible
            ansible-playbook -i inventory.txt configure-server.yml -vv
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1
      # Here's where you will add some code to rollback on failure     
      - destroy-environment:
          workflowid: "${CIRCLE_WORKFLOW_ID:0:7}"
#########################RUNS-MIGRATIONS#####################################
  run-migrations:
    docker:
      # Docker image here that supports NodeJS
      #- image: circleci/node:13.8.0
      - image: cimg/node:18.4.0
    steps:
      # Checkout code from git
      - checkout
      - restore_cache:
          keys: [backend-build]
      #- attach_workspace:
      #    at: ~/ 
      - run:
          name: Install AWS CLI dependencies
      #    # working_directory: /tmp
          command: |
            sudo apt-get update
            sudo apt-get install python3 -y 
            sudo apt-get install python3-pip -y
            sudo pip3 install awscli
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1
      - run:
          name: install npm
          command: |
            cd backend
            npm install
      - run:
          name: install other dependencies
          command: |
            npm install typescript
            npm --update install python3 npm  
      - run:
          name: Run migrations
          no_output_timeout: 20m
          command: |
            # Your code here
            cd backend
            npm run migrations > migrations_dump.txt
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1
      - run:
          name: Send migration results to kvdb
          command: |
            # Your code here
            if grep -q "has been executed successfully." backend/migrations_dump.txt
            then
              curl  https://kvdb.io/97DDVfQqUVMSzD5WALik4Y/values/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
            fi
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1
    # Here's where you will add some code to rollback on failure  
      - destroy-environment:
          workflowid: "${CIRCLE_WORKFLOW_ID:0:7}"
      #- revert-migrations    
#########################DEPLOY-FRONTEND#####################################
  deploy-frontend:
    docker:
      # Docker image here that supports AWS CLI
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      - restore_cache:
          key: frontend-build
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            # your code here
            sudo apt-get install tar -y
            sudo apt-get install gzip -y
            sudo apt-get install git -y
            sudo apt-get install ansible -y
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1 
      - run:
          name: Installing the AWS CLI
          command: |
            # your code here
            sudo apt-get update
            sudo apt install python3 -y 
            sudo apt-get install unzip  -y
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1 
      - run:
          name: get backend url
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query "Reservations[].Instances[*].PublicIpAddress" --output text --region us-east-1)
            export API_URL="http://${BACKEND_IP}:3030"
            echo "API_URL = ${API_URL}" >> "frontend/.env"
            echo API_URL="http://${BACKEND_IP}:3030" >> "frontend/.env"
            cat frontend/.env    
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1         
      - run: 
          name: deploy frontend objects
          command: |
            cd frontend
            npm install
            npm run build
            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1  
    # Here's where you will add some code to rollback on failure  
      - destroy-environment:
          workflowid: "${CIRCLE_WORKFLOW_ID:0:7}"
      - revert-migrations 
#########################DEPLOY-BACKEND######################################
  deploy-backend:
    docker:
      # Docker image here that supports Ansible
      #- image: circleci/node:13.8.0
      - image: python:3.11-rc-alpine
    steps:
      # Checkout code from git
      - checkout
      - restore_cache:
          key: backend-build
      # Add ssh keys with fingerprint
      - add_ssh_keys:
          fingerprints:
            - "a1:6f:c8:51:94:d4:0c:fd:45:00:67:75:29:c4:cd:2f"
      # attach workspace
      - attach_workspace:
          at: ~/
      - run:
          name: Install tar, gzip and awscli
          command:  |
            apk add tar gzip 
            apk update pip3
            pip3 install awscli
            apk add --update curl
            apk add --update nodejs npm
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1 
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible 
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1  
      - run:
          name: Deploy backend
          command: |
            # your code here
            cd backend
            npm i
            npm run build
            cd ..
            tar -C backend -czvf artifact.tar.gz .
            cd .circleci/ansible
            echo "Contents  of the inventory.txt file is -------"
            cat inventory.txt
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook -i inventory.txt deploy-backend.yml
      - slack/notify:
          channel: udapeople
          event: fail
          template: basic_fail_1
      # Here's where you will add some code to rollback on failure  
      - destroy-environment:
          workflowid: "${CIRCLE_WORKFLOW_ID:0:7}" 
      - revert-migrations:
          workflowid: "${CIRCLE_WORKFLOW_ID:0:7}"

  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - run: sleep 60
      - checkout
      - run:
          name: Install dependencies
          command: |
             apk add --update curl
             apk update pip3
             pip3 install awscli
      - run:
          name: Backend smoke test.
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --output text)
            export API_URL="http://${BACKEND_IP}:3030"
            echo "${API_URL}"
            if curl "${API_URL}/api/status" | grep "ok"
            then
              return 0
            else
              return 1
            fi
      - run:
          name: Frontend smoke test.
          command: |
            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
            echo ${URL} 
            if curl -s ${URL} | grep "Welcome"
            then
            # Change this to 0 after the job fails
              return 0
            else
              return 1
            fi
      
      - destroy-environment
      - revert-migrations 
workflows:
  test-and-deploy:
    jobs:
      - build-frontend:
          context: slack-context
      - build-backend:
          context: slack-context
      - test-frontend:
          requires: [build-frontend]
          context: slack-context
      - test-backend:
          requires: [build-backend]
          context: slack-context
      - scan-backend:
          requires: [build-backend]
          context: slack-context
      - scan-frontend:
          requires: [build-frontend]
          context: slack-context
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          context: slack-context
      - configure-infrastructure:
          requires: [deploy-infrastructure]
          context: slack-context
      - run-migrations:
          requires: [configure-infrastructure]
          context: slack-context
      - deploy-frontend:
          requires: [run-migrations]
          context: slack-context
      - deploy-backend:
          requires: [run-migrations]
          context: slack-context
      - smoke-test:
          requires: [deploy-backend, deploy-frontend]
          context: slack-context
      #- cloudfront-update:
         # requires: [smoke-test]
      #- cleanup:
       #   requires: [cloudfront-update]